export enum WalletState {
	NOT_READY = 'NOT_READY',
	READY = 'READY',
	NOT_CONNECTED = 'NOT_CONNECTED',
	CONNECTED = 'CONNECTED',
	CONNECTING = 'CONNECTING',
	DISCONNECTING = 'DISCONNECTING',
	DISCONNECTED = 'DISCONNECTED',
	ERROR = 'ERROR',
}
